_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.7.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 1
epochs:
    value: 20
learning_rate:
    value: 0.0001
use_evo2:
    value: true
